In [13]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
textos_dummy = [
    'esse texto e bom nao possui ruidos foi escrito hoje 04/08/2023',
    '# asd 32$#$ 43 %#$@# $ @#'
]

labels = [0, 1]

In [11]:
depara_emb =  {'vowels': 1, 'consonants': 2, 'espace': 0, 'digits': 3, 'punctuations': 4, 'pad': -2, 'unk': -1}
def transform_text(text):
    vowels = 'aeiou'
    consonants = 'bcdfghjklmnpqrstvwxyz'
    digits = '0123456789'
    punctuations = '.,;:!?'
    
    transformed_list = []
    for char in text:
        if char in vowels:
            transformed_list.append(depara_emb['vowels'])
        elif char in consonants:
            transformed_list.append(depara_emb['consonants'])
        elif char == ' ':
            transformed_list.append(depara_emb['espace'])
        elif char in digits:
            transformed_list.append(depara_emb['digits'])
        elif char in punctuations:
            transformed_list.append(depara_emb['punctuations'])
        else:
            transformed_list.append(depara_emb['unk'])
    
    return transformed_list

def fill_list(lst, limit:int = 100):
    while len(lst) < limit:
        lst.append(depara_emb['pad'])
    return lst

# Exemplo de uso:
resultado = transform_text(textos_dummy[1])
print(resultado)

[-1, 0, 1, 2, 2, 0, 3, 3, -1, -1, -1, 0, 3, 3, 0, -1, -1, -1, -1, -1, 0, -1, 0, -1, -1]


In [58]:
data = list(zip(textos_dummy, labels))

In [64]:
exemplo_texts = [(fill_list(transform_text(x[0])), x[1]) for x in data]

In [66]:
# exemplo_texts

In [70]:
exemplo_texts

[([1,
   2,
   2,
   1,
   0,
   2,
   1,
   2,
   2,
   1,
   0,
   1,
   0,
   2,
   1,
   2,
   0,
   2,
   1,
   1,
   0,
   2,
   1,
   2,
   2,
   1,
   1,
   0,
   2,
   1,
   1,
   2,
   1,
   2,
   0,
   2,
   1,
   1,
   0,
   1,
   2,
   2,
   2,
   1,
   2,
   1,
   0,
   2,
   1,
   2,
   1,
   0,
   3,
   3,
   -1,
   3,
   3,
   -1,
   3,
   3,
   3,
   3,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2],
  0),
 ([-1,
   0,
   1,
   2,
   2,
   0,
   3,
   3,
   -1,
   -1,
   -1,
   0,
   3,
   3,
   0,
   -1,
   -1,
   -1,
   -1,
   -1,
   0,
   -1,
   0,
   -1,
   -1,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
   -2,
  

In [68]:
exemplo_texts[0][1]

0

In [41]:
def transform_to_tensor(vetor, num_quebras, label):
    tamanho_vetor = len(vetor)
    quebras = tamanho_vetor // num_quebras
    quebra = [i * quebras for i in range(num_quebras)] + [tamanho_vetor]
    tensor_quebras = [vetor[quebra[i]:quebra[i+1]] for i in range(num_quebras)]
    return torch.tensor(tensor_quebras), torch.full((1, num_quebras), label)

In [71]:
resultados = [transform_to_tensor(vetor=x[0], num_quebras=2, label=x[1]) for x in exemplo_texts]

In [72]:
resultados

[(tensor([[ 1,  2,  2,  1,  0,  2,  1,  2,  2,  1,  0,  1,  0,  2,  1,  2,  0,  2,
            1,  1,  0,  2,  1,  2,  2,  1,  1,  0,  2,  1,  1,  2,  1,  2,  0,  2,
            1,  1,  0,  1,  2,  2,  2,  1,  2,  1,  0,  2,  1,  2],
          [ 1,  0,  3,  3, -1,  3,  3, -1,  3,  3,  3,  3, -2, -2, -2, -2, -2, -2,
           -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
           -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2]]),
  tensor([[0, 0]])),
 (tensor([[-1,  0,  1,  2,  2,  0,  3,  3, -1, -1, -1,  0,  3,  3,  0, -1, -1, -1,
           -1, -1,  0, -1,  0, -1, -1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
           -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
          [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
           -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
           -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2]]),
  tensor([[1, 1]]))]

In [42]:
transform_to_tensor(exemplo_text, num_quebras=2, label=1)

(tensor([[-1,  0,  1,  2,  2,  0,  3,  3, -1, -1, -1,  0,  3,  3,  0, -1, -1, -1,
          -1, -1,  0, -1,  0, -1, -1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
          -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
         [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
          -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
          -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2]]),
 tensor([[1, 1]]))

In [ ]:
# faça a função retornar [[(tensor palavras, label), (tensor palavras, label)], [(tensor palavras, label), (tensor palavras, label)]]
[transform_to_tensor]