In [1]:
import torch

In [2]:
matrix = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]]])
matrix

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [8]:
matrix.shape

torch.Size([2, 2, 2])

In [17]:
matrix[:,0,:]

tensor([[1, 2],
        [5, 6]])

In [11]:
# each element of the first matrix plus the corresponding element in the second matrix
torch.sum(matrix, dim=0)

tensor([[ 6,  8],
        [10, 12]])

In [6]:
# sum of the elements in the first column of the first matrix becomes the first element of the resulting matrix and so on
torch.sum(matrix, dim=1)

tensor([[ 4,  6],
        [12, 14]])

In [12]:
# sum of the elements in the first row of the first matrix becomes the first element of the resulting matrix and so on
torch.sum(matrix, dim=2)

tensor([[ 3,  7],
        [11, 15]])

In [10]:
torch.sum(matrix)

tensor(36)

In [22]:
a_ = torch.tensor([[1,2,3,4,5]])

In [23]:
a_.shape

torch.Size([1, 5])

In [24]:
a_.ndim

2