In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [34]:
# 1d vector
example_tensor = torch.tensor([100, 1, -100])
example_tensor

tensor([ 100,    1, -100])

In [35]:
# using torch.sigmoid
torch.sigmoid(example_tensor)

tensor([1.0000, 0.7311, 0.0000])

In [36]:
# using nn.Sigmoid
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(example_tensor)

tensor([1.0000, 0.7311, 0.0000])

In [37]:
# using F.sigmoid
F.sigmoid(example_tensor)

tensor([1.0000, 0.7311, 0.0000])

***

In [38]:
# 2d vector
example_tensor = torch.tensor([[100, 1, -100], [100, 1, -100]])
example_tensor

tensor([[ 100,    1, -100],
        [ 100,    1, -100]])

In [39]:
# using torch.sigmoid
torch.sigmoid(example_tensor)

tensor([[1.0000, 0.7311, 0.0000],
        [1.0000, 0.7311, 0.0000]])

In [40]:
# using nn.Sigmoid
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(example_tensor)

tensor([[1.0000, 0.7311, 0.0000],
        [1.0000, 0.7311, 0.0000]])

In [41]:
# using F.sigmoid
F.sigmoid(example_tensor)

tensor([[1.0000, 0.7311, 0.0000],
        [1.0000, 0.7311, 0.0000]])

***

In [18]:
# Changing the axis (dim)
torch.sigmoid(example_tensor, dim=1)

TypeError: sigmoid() got an unexpected keyword argument 'dim'