In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [16]:
# 1d vector
example_tensor = torch.tensor([3, 3, 3], dtype=torch.long).float()
example_tensor

tensor([3., 3., 3.])

In [17]:
# using torch.softmax
torch.softmax(example_tensor, dim=0)

tensor([0.3333, 0.3333, 0.3333])

In [18]:
# using nn.Sigmoid
softmax_layer = nn.Softmax(dim=0)
softmax_layer(example_tensor)

tensor([0.3333, 0.3333, 0.3333])

In [23]:
# using F.sigmoid
F.softmax(example_tensor, dim=0)

tensor([0.3333, 0.3333, 0.3333])

***

In [52]:
# 2d vector
example_tensor = torch.tensor([[3, 3, 3], [1, 2, 3]], dtype=torch.long).float()
example_tensor

tensor([[3., 3., 3.],
        [1., 2., 3.]])

In [32]:
# using torch.softmax
torch.softmax(example_tensor, dim=1)

tensor([[0.3333, 0.3333, 0.3333],
        [0.0900, 0.2447, 0.6652]])

In [33]:
# using nn.Sigmoid
softmax_layer = nn.Softmax(dim=1)
softmax_layer(example_tensor)

tensor([[0.3333, 0.3333, 0.3333],
        [0.0900, 0.2447, 0.6652]])

In [34]:
# using F.sigmoid
F.softmax(example_tensor, dim=1)

tensor([[0.3333, 0.3333, 0.3333],
        [0.0900, 0.2447, 0.6652]])

***

In [54]:
# Changing the axis (dim)
F.softmax(example_tensor, dim=0)

tensor([[0.8808, 0.7311, 0.5000],
        [0.1192, 0.2689, 0.5000]])

In [38]:
# taking a vector with high dimensionality
example_tensor = torch.tensor([[[[[[[3, 3, 3], [1, 2, 3]]]]]]], dtype=torch.long).float()

In [39]:
example_tensor

tensor([[[[[[[3., 3., 3.],
             [1., 2., 3.]]]]]]])

In [43]:
example_tensor.shape

torch.Size([1, 1, 1, 1, 1, 2, 3])

In [42]:
# Changing the axis (dim)
F.softmax(example_tensor, dim=0)

tensor([[[[[[[1., 1., 1.],
             [1., 1., 1.]]]]]]])

In [45]:
# even with this strange vector we can get the row and column
F.softmax(example_tensor, dim=-1)  # row

tensor([[[[[[[0.3333, 0.3333, 0.3333],
             [0.0900, 0.2447, 0.6652]]]]]]])

In [46]:
F.softmax(example_tensor, dim=-2)  # col

tensor([[[[[[[0.8808, 0.7311, 0.5000],
             [0.1192, 0.2689, 0.5000]]]]]]])